
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('dog_table').del()
    .then(function () {
      // Inserts seed entries
      return knex('dog_table').insert([
        {
          id: 1, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Max', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Max near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 2, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Bella', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Bella near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 3, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Charlie', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Charlie near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 4, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Luna', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Luna near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 5, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Cooper', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Cooper near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 6, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Lucy', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Lucy near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 7, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Buddy', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Buddy near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 8, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Daisy', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Daisy near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 9, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Rocky', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Rocky near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 10, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Lily', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Lily near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 11, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Milo', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Milo near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 12, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Zoe', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Zoe near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 13, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Jack', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Jack near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 14, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Lola', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Lola near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 15, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Bear', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Bear near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 16, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Molly', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Molly near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 17, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Duke', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Duke near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 18, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Sadie', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Sadie near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 19, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Teddy', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Teddy near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 20, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Bailey', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Bailey near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 21, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Tucker', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Tucker near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 22, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Stella', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Stella near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 23, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Bentley', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Bentley near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 24, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Roxy', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Roxy near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 25, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Beau', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Beau near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 26, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Chloe', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Chloe near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 27, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Leo', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't letLeo near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 28, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Gus', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Gus near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 29, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Lexi', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Lexi near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 30, 
          owner_id: 1, 
          feedback_id: 1, 
          name: 'Jake', 
          breed: 'Labradore', 
          sex: 'Does it matter?', 
          age: '1,000,000', 
          size: 'Medium', 
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Jake near food...",
          photo: 'placeHolder',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
      ]);
    });
};
