
exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('dog_table').del()
    .then(function () {
      // Inserts seed entries
      return knex('dog_table').insert([
        {
          id: 1,
          owner_id: 1,
          feedback_id: 1,
          name: 'Max',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Max near food...",
          photo: 'https://images.pexels.com/photos/1001976/pexels-photo-1001976.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 2,
          owner_id: 2,
          feedback_id: 1,
          name: 'Bella',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Bella near food...",
          photo: 'https://images.pexels.com/photos/247968/pexels-photo-247968.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 3,
          owner_id: 3,
          feedback_id: 1,
          name: 'Charlie',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Charlie near food...",
          photo: 'https://images.pexels.com/photos/1591939/pexels-photo-1591939.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 4,
          owner_id: 2,
          feedback_id: 1,
          name: 'Luna',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Luna near food...",
          photo: 'https://images.pexels.com/photos/2449536/pexels-photo-2449536.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 5,
          owner_id: 3,
          feedback_id: 1,
          name: 'Cooper',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Cooper near food...",
          photo: 'https://images.pexels.com/photos/1485637/pexels-photo-1485637.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 6,
          owner_id: 1,
          feedback_id: 1,
          name: 'Lucy',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Lucy near food...",
          photo: 'https://images.pexels.com/photos/2802421/pexels-photo-2802421.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 7,
          owner_id: 1,
          feedback_id: 1,
          name: 'Buddy',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Buddy near food...",
          photo: 'https://images.pexels.com/photos/551628/pexels-photo-551628.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 8,
          owner_id: 1,
          feedback_id: 1,
          name: 'Daisy',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Daisy near food...",
          photo: 'https://images.pexels.com/photos/38632/dog-race-fun-animal-38632.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 9,
          owner_id: 1,
          feedback_id: 1,
          name: 'Rocky',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Rocky near food...",
          photo: 'https://images.pexels.com/photos/264005/pexels-photo-264005.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 10,
          owner_id: 1,
          feedback_id: 1,
          name: 'Lily',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Lily near food...",
          photo: 'https://images.pexels.com/photos/59849/schnauzer-miniature-schnauzer-dog-running-59849.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 11,
          owner_id: 1,
          feedback_id: 1,
          name: 'Milo',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Milo near food...",
          photo: 'https://images.pexels.com/photos/2423371/pexels-photo-2423371.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 12,
          owner_id: 1,
          feedback_id: 1,
          name: 'Zoe',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Zoe near food...",
          photo: 'https://images.pexels.com/photos/3361739/pexels-photo-3361739.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 13,
          owner_id: 1,
          feedback_id: 1,
          name: 'Jack',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Jack near food...",
          photo: 'https://images.pexels.com/photos/3763313/pexels-photo-3763313.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 14,
          owner_id: 1,
          feedback_id: 1,
          name: 'Lola',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Lola near food...",
          photo: 'https://images.pexels.com/photos/3590443/pexels-photo-3590443.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 15,
          owner_id: 1,
          feedback_id: 1,
          name: 'Bear',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Bear near food...",
          photo: 'https://images.pexels.com/photos/1058498/pexels-photo-1058498.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 16,
          owner_id: 1,
          feedback_id: 1,
          name: 'Molly',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Molly near food...",
          photo: 'https://images.pexels.com/photos/1458916/pexels-photo-1458916.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 17,
          owner_id: 1,
          feedback_id: 1,
          name: 'Duke',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Duke near food...",
          photo: 'https://images.pexels.com/photos/3785356/pexels-photo-3785356.png?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 18,
          owner_id: 1,
          feedback_id: 1,
          name: 'Sadie',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Sadie near food...",
          photo: 'https://images.pexels.com/photos/2737393/pexels-photo-2737393.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 19,
          owner_id: 1,
          feedback_id: 1,
          name: 'Teddy',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Teddy near food...",
          photo: 'https://images.pexels.com/photos/532310/pexels-photo-532310.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 20,
          owner_id: 1,
          feedback_id: 1,
          name: 'Bailey',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Bailey near food...",
          photo: 'https://images.pexels.com/photos/333083/pexels-photo-333083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 21,
          owner_id: 1,
          feedback_id: 1,
          name: 'Tucker',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Tucker near food...",
          photo: 'https://images.pexels.com/photos/3104709/pexels-photo-3104709.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 22,
          owner_id: 1,
          feedback_id: 1,
          name: 'Stella',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Stella near food...",
          photo: 'https://images.pexels.com/photos/1954515/pexels-photo-1954515.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 23,
          owner_id: 1,
          feedback_id: 1,
          name: 'Bentley',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Bentley near food...",
          photo: 'https://images.pexels.com/photos/1906153/pexels-photo-1906153.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 24,
          owner_id: 1,
          feedback_id: 1,
          name: 'Roxy',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Roxy near food...",
          photo: 'https://images.pexels.com/photos/1596579/pexels-photo-1596579.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 25,
          owner_id: 1,
          feedback_id: 1,
          name: 'Beau',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Beau near food...",
          photo: 'https://images.pexels.com/photos/164186/pexels-photo-164186.jpeg?auto=compress&cs=tinysrgb&dpr=https://images.pexels.com/photos/164186/pexels-photo-164186.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 26,
          owner_id: 1,
          feedback_id: 1,
          name: 'Chloe',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Chloe near food...",
          photo: 'https://images.pexels.com/photos/2007/animal-dog-pet-cute.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 27,
          owner_id: 1,
          feedback_id: 1,
          name: 'Leo',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Leo near food...",
          photo: 'https://images.pexels.com/photos/257519/pexels-photo-257519.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 28,
          owner_id: 1,
          feedback_id: 1,
          name: 'Gus',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Gus near food...",
          photo: 'https://images.pexels.com/photos/3196887/pexels-photo-3196887.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 29,
          owner_id: 1,
          feedback_id: 1,
          name: 'Lexi',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Lexi near food...",
          photo: 'https://images.pexels.com/photos/2664417/pexels-photo-2664417.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
        {
          id: 30,
          owner_id: 1,
          feedback_id: 1,
          name: 'Jake',
          breed: '',
          sex: 'Does it matter?',
          age: '',
          size: 'Medium',
          activity_requirements: '30min walk',
          good_with_other_dogs: true,
          special_requirements: "Don't let Jake near food...",
          photo: 'https://images.adagio.com/images2/custom_blends/139293.jpg',
          vet_name: 'Ngaio Vetenerian',
          vet_contact: 02222222222,
        },
      ]);
    });
};
