
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('owner_table').del()
    .then(function () {
      // Inserts seed entries
      return knex('owner_table').insert([
        {
          id: 1, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 2, 
          feedback_id: 1, 
          first_name: 'John', 
          last_name: 'Smith', 
          photo: 'https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'JohnSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 3, 
          feedback_id: 1, 
          first_name: 'Emma', 
          last_name: 'Hughes', 
          photo: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260', 
          location: 'Ngaio', 
          email: 'EmmaHughes@gmail.com', 
          hash: '', 
        },
        {
          id: 4, 
          feedback_id: 1, 
          first_name: 'Sophia', 
          last_name: 'Day', 
          photo: 'https://images.pexels.com/photos/1024311/pexels-photo-1024311.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'SophiaDay@gmail.com', 
          hash: '', 
        },
        {
          id: 5, 
          feedback_id: 1, 
          first_name: 'Daniel', 
          last_name: 'Allen', 
          photo: 'https://images.pexels.com/photos/1121796/pexels-photo-1121796.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'DanielAllen@gmail.com', 
          hash: '', 
        },
        {
          id: 6, 
          feedback_id: 1, 
          first_name: 'Stefan', 
          last_name: 'Butt', 
          photo: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'StefanButt@gmail.com', 
          hash: '', 
        },
        {
          id: 7, 
          feedback_id: 1, 
          first_name: 'Christopher', 
          last_name: 'Penlington', 
          photo: 'https://images.pexels.com/photos/839011/pexels-photo-839011.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'CHristopherPenlington@gmail.com', 
          hash: '', 
        },
        {
          id: 8, 
          feedback_id: 1, 
          first_name: 'Sarah', 
          last_name: 'McMillan', 
          photo: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'SarahMcMillan@gmail.com', 
          hash: '', 
        },
        {
          id: 9, 
          feedback_id: 1, 
          first_name: 'Holly', 
          last_name: 'Jane', 
          photo: 'https://images.pexels.com/photos/38554/girl-people-landscape-sun-38554.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'HollyJane@gmail.com', 
          hash: '', 
        },
        {
          id: 10, 
          feedback_id: 1, 
          first_name: 'Nathan', 
          last_name: 'Steel', 
          photo: 'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'NathanSteel@gmail.com', 
          hash: '', 
        },
        {
          id: 11, 
          feedback_id: 1, 
          first_name: 'Kevin', 
          last_name: 'James-Smith', 
          photo: 'https://images.pexels.com/photos/936229/pexels-photo-936229.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'KevinJamesSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 12, 
          feedback_id: 1, 
          first_name: 'Joanna', 
          last_name: 'Waller', 
          photo: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'JoannaWaller@gmail.com', 
          hash: '', 
        },
        {
          id: 13, 
          feedback_id: 1, 
          first_name: 'Jessica', 
          last_name: 'Bell', 
          photo: 'https://images.pexels.com/photos/1036620/pexels-photo-1036620.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'JessicaBell@gmail.com', 
          hash: '', 
        },
        {
          id: 14, 
          feedback_id: 1, 
          first_name: 'Anna', 
          last_name: '', 
          photo: 'https://images.pexels.com/photos/756453/pexels-photo-756453.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 15, 
          feedback_id: 1, 
          first_name: 'Olivia', 
          last_name: 'Engel', 
          photo: 'https://images.pexels.com/photos/709790/pexels-photo-709790.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 16, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 17, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 18, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 19, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 20, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 21, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 22, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 23, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 24, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 25, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 26, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 27, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 28, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 29, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
        {
          id: 30, 
          feedback_id: 1, 
          first_name: 'Steve', 
          last_name: 'Smith', 
          photo: 'placeHolder', 
          location: 'Ngaio', 
          email: 'SteveSmith@gmail.com', 
          hash: '', 
        },
      ]);
    });
};
