
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('walker_table').del()
    .then(function () {
      // Inserts seed entries
      return knex('walker_table').insert([
        {
          id: 1, 
          feedback_id: 1, 
          username: 'bof', 
          first_name: 'Mary', 
          last_name: 'Wells', 
          blurb: 'Loves long walks on the beach', 
          location: 'Ngaio', 
          email: 'marywells@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 2, 
          feedback_id: 1, 
          username: 'user123', 
          first_name: 'James', 
          last_name: 'Jenkins', 
          blurb: 'Dog lover', 
          location: 'Aro Valley', 
          email: 'jamesjenkins@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 3, 
          feedback_id: 1, 
          username: 'jenny', 
          first_name: 'Jennifer', 
          last_name: 'Soo', 
          blurb: 'Happiest when strolling the hills with mans best friend', 
          location: 'Berhampore', 
          email: 'jennifersoo@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 4, 
          feedback_id: 1, 
          username: 'bobbity', 
          first_name: 'Robert', 
          last_name: 'Wellington', 
          blurb: 'Friendly guy who is a sucker for big dogs', 
          location: 'Aro Valley', 
          email: 'robertwellington@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/941693/pexels-photo-941693.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 5, 
          feedback_id: 1, 
          username: 'liz', 
          first_name: 'Elizabeth', 
          last_name: 'Paul', 
          blurb: 'Super active, enjoys long walks', 
          location: 'Brooklyn', 
          email: 'elizabethpaul@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/3373398/pexels-photo-3373398.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 6, 
          feedback_id: 1, 
          username: 'mikeyboy', 
          first_name: 'Michael', 
          last_name: 'Matthews', 
          blurb: 'Senior who loves the companion of a furry friend', 
          location: 'Hataitai', 
          email: 'michaelmatthews@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/834863/pexels-photo-834863.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 7, 
          feedback_id: 1, 
          username: 'babz', 
          first_name: 'Barb', 
          last_name: 'Thomas', 
          blurb: 'Loves long walks on the beach', 
          location: 'Brooklyn', 
          email: 'barbthomas@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/38554/girl-people-landscape-sun-38554.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 8, 
          feedback_id: 1, 
          username: 'suz', 
          first_name: 'Susan', 
          last_name: 'Go', 
          blurb: 'Lover of any dog, any size', 
          location: 'Ngaio', 
          email: 'susango@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 9, 
          feedback_id: 1, 
          username: 'daveyjoneslocker', 
          first_name: 'David', 
          last_name: 'Williams', 
          blurb: 'Big dogs, small, dogs, medium dogs', 
          location: 'Houghton Bay', 
          email: 'davidwilliams@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/868113/pexels-photo-868113.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 10, 
          feedback_id: 1, 
          username: 'tobefrankwithyou', 
          first_name: 'Frank', 
          last_name: 'Burrows', 
          blurb: 'Not a cat person', 
          location: 'Island Bay', 
          email: 'frankburrows@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/412840/pexels-photo-412840.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 11, 
          feedback_id: 1, 
          username: 'specialj', 
          first_name: 'Jono', 
          last_name: 'Clark', 
          blurb: 'Dogs best friend', 
          location: 'Karori', 
          email: 'jonoclark@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/373899/pexels-photo-373899.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 12, 
          feedback_id: 1, 
          username: 'specialk', 
          first_name: 'Karen', 
          last_name: 'Franco', 
          blurb: 'Puppies make me smile', 
          location: 'Island Bay', 
          email: 'karenfranco@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/1197132/pexels-photo-1197132.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 13, 
          feedback_id: 1, 
          username: 'joebo', 
          first_name: 'Joseph', 
          last_name: 'Step', 
          blurb: 'Enjoys running along side fast dogs', 
          location: 'Kelburn', 
          email: 'josephstep@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/1139743/pexels-photo-1139743.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 14, 
          feedback_id: 1, 
          username: 'sezzy', 
          first_name: 'Sarah', 
          last_name: 'Don', 
          blurb: 'Loves long walks on the beach', 
          location: 'Kilbirnie', 
          email: 'sarahdon@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 15, 
          feedback_id: 1, 
          username: 'nancydrew', 
          first_name: 'Nancy', 
          last_name: 'Noels', 
          blurb: 'Loves long walks on the beach', 
          location: 'Ngaio', 
          email: 'nancynoels@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/372042/pexels-photo-372042.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 16, 
          feedback_id: 1, 
          username: 'stalk', 
          first_name: 'Jack', 
          last_name: 'Bean', 
          blurb: 'Loves long walks on the beach', 
          location: 'Houghton Valley', 
          email: 'jackbean@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/709188/pexels-photo-709188.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 17, 
          feedback_id: 1, 
          username: 'lol', 
          first_name: 'Ash', 
          last_name: 'Lee', 
          blurb: 'Loves long walks on the beach', 
          location: 'Ngaio', 
          email: 'ashlee@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/948873/pexels-photo-948873.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 18, 
          feedback_id: 1, 
          username: 'toppgun', 
          first_name: 'Jim', 
          last_name: 'Tim', 
          blurb: 'Loves long walks on the beach', 
          location: 'Melrose', 
          email: 'jimtim@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 19, 
          feedback_id: 1, 
          username: 'frida', 
          first_name: 'Frida', 
          last_name: 'Robuck', 
          blurb: 'Loves long walks on the beach', 
          location: 'Melrose', 
          email: 'fridarobuck@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/774095/pexels-photo-774095.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 20, 
          feedback_id: 1, 
          username: 'joe', 
          first_name: 'Joe', 
          last_name: 'Dirr', 
          blurb: 'Loves long walks on the beach', 
          location: 'Ngaio', 
          email: 'joedirr@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 21, 
          feedback_id: 1, 
          username: 'sammi', 
          first_name: 'Sammi', 
          last_name: 'Loft', 
          blurb: 'Loves long walks on the beach', 
          location: 'Newtown', 
          email: 'sammiloft@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/1666073/pexels-photo-1666073.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 22, 
          feedback_id: 1, 
          username: 'eric', 
          first_name: 'Eric', 
          last_name: 'Legg', 
          blurb: 'Loves long walks on the beach', 
          location: 'Lyall Bay', 
          email: 'ericlegg@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 23, 
          feedback_id: 1, 
          username: 'ela', 
          first_name: 'Pam', 
          last_name: 'Coop', 
          blurb: 'Loves long walks on the beach', 
          location: 'Newtown', 
          email: 'pamcoop@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 24, 
          feedback_id: 1, 
          username: 'wellwellnick', 
          first_name: 'Nick', 
          last_name: 'Wells', 
          blurb: 'Loves long walks on the beach', 
          location: 'Lyall Bay', 
          email: 'nickwells@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/936119/pexels-photo-936119.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 25, 
          feedback_id: 1, 
          username: 'bradanna', 
          first_name: 'Anna', 
          last_name: 'Brad', 
          blurb: 'Loves long walks on the beach', 
          location: 'Melrose', 
          email: 'annabrad@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/1090387/pexels-photo-1090387.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 26, 
          feedback_id: 1, 
          username: 'justintime', 
          first_name: 'Justin', 
          last_name: 'Lake', 
          blurb: 'Loves long walks on the beach', 
          location: 'Miramar', 
          email: 'justinlake@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 27, 
          feedback_id: 1,
          username: 'had-little-lamb',  
          first_name: 'Mary', 
          last_name: 'Wells', 
          blurb: 'Loves long walks on the beach', 
          location: 'Ngaio', 
          email: 'testemail@testemail.nz', 
          hash: '', 
          photo: 'placeHolder',
        },
        {
          id: 28, 
          feedback_id: 1, 
          username: 'what?', 
          first_name: 'Nicky', 
          last_name: 'Wombat', 
          blurb: 'Loves long walks on the beach', 
          location: 'Kelburn', 
          email: 'nickywombat@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/2323183/pexels-photo-2323183.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 29, 
          feedback_id: 1, 
          username: 'usernamesarehard', 
          first_name: 'Gary', 
          last_name: 'Bouy', 
          blurb: 'Loves long walks on the beach', 
          location: 'Melrose', 
          email: 'garybouy@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/25758/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
        {
          id: 30, 
          feedback_id: 1, 
          username: 'auth-is-hard', 
          first_name: 'Ruth', 
          last_name: 'Struth', 
          blurb: 'Loves long walks on the beach', 
          location: 'Island Bay', 
          email: 'ruthstruth@gmail.com', 
          hash: '', 
          photo: 'https://images.pexels.com/photos/789822/pexels-photo-789822.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        },
      ]);
    });
};
